name: Build Radxa E20C

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ImmortalWrt
        uses: actions/checkout@v3
        with:
          repository: immortalwrt/immortalwrt
          submodules: recursive

      - name: Add Radxa E20C Support
        run: |
          # 克隆设备支持仓库
          git clone https://github.com/ac220/openwrt_packit
          
          # 复制Rockchip平台文件
          mkdir -p target/linux/rockchip
          cp -rf openwrt_packit/files/target/linux/rockchip/* target/linux/rockchip/
          
          # 复制其他必要文件（如有）
          [ -d "openwrt_packit/files/package" ] && cp -rf openwrt_packit/files/package/* package/

      - name: Build Firmware
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make menuconfig
          make -j$(nproc) V=s
